"""Generate sql/01_create_raw_tables.sql from the Kaggle CSV headers.

The transaction file has 394 columns, so writing CREATE TABLE by hand would be
error-prone. This script reads the header plus a sample of rows, decides for
each column whether it is numeric or text, and writes the DDL.

Run once:  python3 src/generate_raw_ddl.py
"""
import csv
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "data" / "raw"
OUT = ROOT / "sql" / "01_create_raw_tables.sql"
SAMPLE_ROWS = 50_000

# Explicit names/types for the key columns; everything else is inferred.
RENAMES = {
    "TransactionID": "transaction_id",
    "isFraud": "is_fraud",
    "TransactionDT": "transaction_dt",
    "TransactionAmt": "transaction_amt",
    "ProductCD": "product_cd",
    "DeviceType": "device_type",
    "DeviceInfo": "device_info",
}
FIXED_TYPES = {
    "transaction_id": "BIGINT PRIMARY KEY",
    "is_fraud": "SMALLINT NOT NULL",
    "transaction_dt": "BIGINT NOT NULL",
    "transaction_amt": "NUMERIC(12, 3) NOT NULL",
}


def to_sql_name(name: str) -> str:
    return RENAMES.get(name, re.sub(r"[^a-z0-9_]", "_", name.lower()))


def is_number(value: str) -> bool:
    try:
        float(value)
        return True
    except ValueError:
        return False


def infer_columns(path: Path) -> list[tuple[str, str]]:
    with path.open(newline="") as f:
        reader = csv.reader(f)
        header = next(reader)
        numeric = [True] * len(header)
        for i, row in enumerate(reader):
            if i >= SAMPLE_ROWS:
                break
            for j, value in enumerate(row):
                if value and numeric[j] and not is_number(value):
                    numeric[j] = False

    columns = []
    for name, num in zip(header, numeric):
        sql_name = to_sql_name(name)
        sql_type = FIXED_TYPES.get(sql_name, "REAL" if num else "TEXT")
        columns.append((sql_name, sql_type))
    return columns


def create_table(table: str, columns: list[tuple[str, str]]) -> str:
    body = ",\n".join(f"    {name} {sql_type}" for name, sql_type in columns)
    return f"DROP TABLE IF EXISTS {table} CASCADE;\nCREATE TABLE {table} (\n{body}\n);\n"


def main() -> None:
    tx = infer_columns(RAW / "train_transaction.csv")
    ident = infer_columns(RAW / "train_identity.csv")
    ident = [(n, "BIGINT PRIMARY KEY" if n == "transaction_id" else t) for n, t in ident]

    OUT.write_text(
        "-- GENERATED by src/generate_raw_ddl.py from the CSV headers. Do not edit by hand.\n"
        "-- Raw layer: one table per Kaggle file, columns exactly as in the CSV.\n\n"
        "CREATE SCHEMA IF NOT EXISTS raw;\n\n"
        + create_table("raw.train_transaction", tx)
        + "\n"
        + create_table("raw.train_identity", ident)
    )
    print(f"Wrote {OUT} ({len(tx)} + {len(ident)} columns)")


if __name__ == "__main__":
    main()
